package cda

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/biodream-llc/perfuse/internal/xtree"
)

// Agreement checks that a document's two halves say the same thing.
//
// Every C-CDA section carries its content twice: a narrative block a clinician
// reads, and coded entries a machine reads. The specification requires them to
// correspond. In practice they frequently do not, because the narrative is
// generated by one part of an EHR and the entries by another, and nothing in the
// usual toolchain compares them - not the schema, not the Schematron, not the
// certification tests, which check that both exist rather than that both agree.
//
// The consequence is a document where a clinician sees one thing and the receiving
// system files another. A penicillin allergy present in the text and absent from
// the entries will not reach the allergy list of the system that imports it, and
// nobody finds out until somebody is prescribed penicillin.
//
// So this compares them. Being useful here means being conservative: a check that
// cries wolf on ordinary wording differences gets switched off, and then it is
// worth nothing. Every finding below is either a structural mismatch that cannot
// be a wording difference, or a term present on one side and absent from the other
// after normalisation.

// Finding is one disagreement.
type Finding struct {
	// Severity is "error", "warning" or "info". Only a genuine contradiction is an
	// error; a term missing from one side is a warning, because it may be a
	// wording difference this check cannot see through.
	Severity string `json:"severity"`

	// Section is which section the finding is in.
	Section string `json:"section"`

	// Kind classifies it, so a recurring pattern can be recognised:
	// "entries-without-narrative", "narrative-without-entries",
	// "term-missing-from-entries", "term-missing-from-narrative",
	// "negation-mismatch", "count-mismatch", "unreferenced-entry".
	Kind string `json:"kind"`

	Message string `json:"message"`

	// Narrative and Coded are the two readings, so somebody can judge for
	// themselves rather than taking the finding's word for it.
	Narrative string `json:"narrative,omitempty"`
	Coded     string `json:"coded,omitempty"`
}

// AgreementReport is the result of checking a document.
type AgreementReport struct {
	Findings []Finding `json:"findings"`

	// Checked is how many sections were compared.
	Checked int `json:"checked"`
	// Skipped is how many were not, with Reasons saying why. A check that
	// silently examined half a document would be misleading.
	Skipped int      `json:"skipped"`
	Reasons []string `json:"reasons,omitempty"`

	Errors   int `json:"errors"`
	Warnings int `json:"warnings"`
}

// Agrees reports whether nothing of consequence was found.
func (r AgreementReport) Agrees() bool { return r.Errors == 0 && r.Warnings == 0 }

// CheckAgreement compares narrative and entries throughout a document.
func CheckAgreement(d *Document) AgreementReport {
	// Findings starts empty rather than nil so it serialises as [], not null. A document whose
	// narrative and entries agree produces none, and that is the normal case.
	report := AgreementReport{Findings: []Finding{}}

	for _, section := range d.Sections {
		label := sectionLabel(section)

		narrative := strings.TrimSpace(section.NarrativeText)
		hasNarrative := narrative != ""
		hasEntries := len(section.Entries) > 0

		// A section explicitly marked absent is consistent by construction.
		if section.NilFlavor != "" {
			report.Skipped++
			report.Reasons = append(report.Reasons,
				fmt.Sprintf("%s: marked %s, so there is nothing to compare", label, nilFlavorMeaning(section.NilFlavor)))
			continue
		}

		if !hasNarrative && !hasEntries {
			report.Skipped++
			report.Reasons = append(report.Reasons, label+": empty on both sides")
			continue
		}

		// One side present and the other missing is structural. It cannot be a
		// wording difference, so it is reported without hedging.
		if hasEntries && !hasNarrative {
			report.add(Finding{
				Severity: "error",
				Section:  label,
				Kind:     "entries-without-narrative",
				Message: fmt.Sprintf("%d coded entr%s but no narrative; a clinician reading this document will not see this information at all",
					len(section.Entries), plural(len(section.Entries), "y", "ies")),
				Coded: describeEntries(section.Entries),
			})
			report.Checked++
			continue
		}

		if hasNarrative && !hasEntries {
			// Which way round this matters depends on the section. In allergies
			// and medications, text without codes means the importing system
			// files nothing, which is the dangerous direction.
			severity := "warning"
			message := "narrative text but no coded entries, so a receiving system will not import this content"
			if section.Kind == "Allergies" || section.Kind == "Medications" || section.Kind == "Problems" {
				severity = "error"
				message = fmt.Sprintf("narrative text but no coded entries. In a %s section this means the "+
					"receiving system imports nothing, while a clinician reading the document sees content",
					strings.ToLower(section.Kind))
			}
			report.add(Finding{
				Severity:  severity,
				Section:   label,
				Kind:      "narrative-without-entries",
				Message:   message,
				Narrative: truncate(narrative, 200),
			})
			report.Checked++
			continue
		}

		report.Checked++
		checkTerms(&report, section, label)
		checkNegation(&report, section, label)
		checkReferences(&report, section, label)
	}

	return report
}

func (r *AgreementReport) add(f Finding) {
	// Cap the findings. A document generated by a badly broken system can
	// disagree in thousands of places, and a report nobody can read is no better
	// than none.
	if len(r.Findings) >= 200 {
		return
	}
	r.Findings = append(r.Findings, f)
	switch f.Severity {
	case "error":
		r.Errors++
	case "warning":
		r.Warnings++
	}
}

// checkTerms compares the significant words on each side.
//
// The comparison is on normalised terms rather than substrings, because the two
// sides legitimately differ in wording: the narrative says "Penicillin G" and the
// entry displays "penicillin". Matching on a stemmed, lower-cased term with common
// clinical noise words removed gets through most of that without inventing
// equivalences.
func checkTerms(report *AgreementReport, section Section, label string) {
	narrativeTerms := significantTerms(section.contentText())

	for _, entry := range flatten(section.Entries) {
		// An organiser groups results; its own code is a panel name that
		// legitimately does not appear in the narrative, which lists the
		// individual results. Checking it would report a defect that is not one.
		if entry.Kind == "Organizer" {
			continue
		}
		// An assertion code carries no substance of its own; the meaning is in the
		// value, which is checked when it is present.
		if strings.EqualFold(entry.Code, "ASSERTION") && entry.ValueName == "" && entry.ValueCode == "" {
			continue
		}

		name := entry.CodeName
		if name == "" {
			name = entry.ValueName
		}
		if strings.EqualFold(name, "ASSERTION") {
			name = entry.ValueName
		}
		if name == "" {
			continue
		}

		// An entry that points at narrative text has already declared its
		// correspondence, and the reference check covers whether it resolves.
		if entry.Text != "" {
			continue
		}

		terms := significantTerms(name)
		if len(terms) == 0 {
			continue
		}

		found := false
		for term := range terms {
			if narrativeTerms[term] {
				found = true
				break
			}
		}
		if found {
			continue
		}

		severity := "warning"
		if section.Kind == "Allergies" {
			// An allergy present in the codes and absent from the text is the
			// case with the clearest path to harm.
			severity = "error"
		}
		report.add(Finding{
			Severity: severity,
			Section:  label,
			Kind:     "term-missing-from-narrative",
			Message: fmt.Sprintf("the coded entry %q does not appear in the narrative; the two halves of this section "+
				"describe different things", entry.Describe()),
			Coded:     entry.Describe(),
			Narrative: truncate(section.NarrativeText, 200),
		})
	}

	// The other direction, restricted to sections where a missed term has a clear
	// consequence. Running it everywhere produces noise, because narrative in a
	// history section is prose full of terms that were never meant to be coded.
	if section.Kind != "Allergies" && section.Kind != "Medications" {
		return
	}

	codedTerms := map[string]bool{}
	for _, entry := range flatten(section.Entries) {
		for term := range significantTerms(entry.CodeName + " " + entry.ValueName) {
			codedTerms[term] = true
		}
	}

	// Only look at capitalised words in the narrative, which in these sections are
	// substance and drug names rather than ordinary prose.
	for _, candidate := range properNouns(section.contentText()) {
		terms := significantTerms(candidate)
		if len(terms) == 0 {
			continue
		}
		matched := false
		for term := range terms {
			if codedTerms[term] {
				matched = true
				break
			}
		}
		if matched {
			continue
		}
		report.add(Finding{
			Severity: "warning",
			Section:  label,
			Kind:     "term-missing-from-entries",
			Message: fmt.Sprintf("the narrative mentions %q but no coded entry does; a receiving system will not import it",
				candidate),
			Narrative: candidate,
			Coded:     describeEntries(section.Entries),
		})
	}
}

// checkNegation looks for a contradiction in direction.
//
// This is the single most consequential mismatch available: the narrative saying a
// patient has no known allergies while an entry records one, or the reverse. Both
// readings are actionable and they disagree about the opposite of the same fact.
func checkNegation(report *AgreementReport, section Section, label string) {
	narrative := strings.ToLower(section.NarrativeText)

	deniesInText := containsAny(narrative,
		"no known allergies", "no known drug allergies", "denies allergies",
		"nka", "nkda", "no allergies", "none known", "no known medication allergies")

	positiveEntries := 0
	negatedEntries := 0
	for _, entry := range flatten(section.Entries) {
		// A nil-flavoured or explicitly negated entry is itself a statement of
		// absence, so it agrees with a denial in the text.
		if entry.NegationInd || entry.NilFlavor != "" {
			negatedEntries++
			continue
		}
		// An entry with no code at all carries no assertion.
		if entry.Code == "" && entry.ValueCode == "" && entry.Value == "" {
			continue
		}
		positiveEntries++
	}

	if deniesInText && positiveEntries > 0 {
		report.add(Finding{
			Severity: "error",
			Section:  label,
			Kind:     "negation-mismatch",
			Message: fmt.Sprintf("the narrative states there are none, but %d coded entr%s a positive finding. "+
				"A clinician reading the document and a system importing it will reach opposite conclusions",
				positiveEntries, plural(positiveEntries, "y records", "ies record")),
			Narrative: truncate(section.NarrativeText, 200),
			Coded:     describeEntries(section.Entries),
		})
		return
	}

	if !deniesInText && positiveEntries == 0 && negatedEntries > 0 &&
		strings.TrimSpace(section.NarrativeText) != "" {
		// The entries say absence and the narrative says something. Worth a
		// mention rather than an error, because the narrative may be describing
		// the absence in words this check does not recognise.
		report.add(Finding{
			Severity: "info",
			Section:  label,
			Kind:     "negation-mismatch",
			Message: "every coded entry records an absence, but the narrative does not use a phrase that states one; " +
				"worth confirming the two agree",
			Narrative: truncate(section.NarrativeText, 200),
		})
	}
}

// checkReferences verifies that an entry pointing at narrative text points at
// something that exists.
//
// A dangling reference is not cosmetic. It is the mechanism by which the two halves
// are linked, and a viewer that follows it shows the reader nothing while appearing
// to work.
func checkReferences(report *AgreementReport, section Section, label string) {
	if section.node == nil {
		return
	}
	text := section.node.First("text")
	if text == nil {
		return
	}

	refs := collectReferences(section.node)

	for _, ref := range refs {
		if ref.target == "" {
			continue
		}
		if findByID(text, ref.target) != nil {
			continue
		}
		report.add(Finding{
			Severity: "warning",
			Section:  label,
			Kind:     "unreferenced-entry",
			Message: fmt.Sprintf("a coded entry points at narrative %q, which does not exist in this section; "+
				"a viewer following the link shows nothing", "#"+ref.target),
			Coded: ref.describe,
		})
	}
}

type entryRef struct {
	target   string
	describe string
}

func collectReferences(section *xtree.Node) []entryRef {
	var out []entryRef
	for _, entry := range section.All("entry") {
		for _, node := range entry.Descendants("reference") {
			value := strings.TrimSpace(node.AttrValue("value"))
			if !strings.HasPrefix(value, "#") {
				continue
			}
			out = append(out, entryRef{target: strings.TrimPrefix(value, "#"), describe: value})
		}
	}
	return out
}

// significantTerms reduces text to comparable terms.
func significantTerms(text string) map[string]bool {
	out := map[string]bool{}

	for _, word := range strings.FieldsFunc(strings.ToLower(text), func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	}) {
		if len(word) < 4 || noiseWords[word] {
			continue
		}
		out[stem(word)] = true
	}
	return out
}

// stem removes the endings that differ between a display name and prose without
// changing the term. It is deliberately crude: anything cleverer would start
// equating things that are not the same, and a false match here means a real
// disagreement goes unreported.
func stem(word string) string {
	for _, suffix := range []string{"ies", "ing", "ed", "es", "s"} {
		if len(word) > len(suffix)+3 && strings.HasSuffix(word, suffix) {
			return word[:len(word)-len(suffix)]
		}
	}
	return word
}

// noiseWords are words that carry no identifying information in clinical text, so
// their presence on both sides proves nothing.
var noiseWords = map[string]bool{
	"the": true, "and": true, "with": true, "without": true, "patient": true,
	"history": true, "unspecified": true, "other": true, "type": true,
	"chronic": true, "acute": true, "left": true, "right": true, "bilateral": true,
	"daily": true, "twice": true, "once": true, "tablet": true, "capsule": true,
	"oral": true, "route": true, "dose": true, "unit": true, "each": true,
	"reaction": true, "allergy": true, "allergic": true, "adverse": true,
	"none": true, "known": true, "product": true, "containing": true,
	"finding": true, "disorder": true, "status": true, "post": true,
	"mg": true, "mcg": true, "ml": true, "code": true, "text": true,
	"observation": true, "result": true, "normal": true, "review": true,
	"date": true, "time": true, "value": true, "name": true, "reported": true,
}

// properNouns pulls capitalised words out of narrative text, which in an allergy
// or medication list are the substance names.
func properNouns(text string) []string {
	var out []string
	seen := map[string]bool{}

	for _, line := range strings.Split(text, "\n") {
		for _, field := range strings.FieldsFunc(line, func(r rune) bool {
			return r == '|' || r == ',' || r == ';' || r == '(' || r == ')'
		}) {
			field = strings.TrimSpace(field)
			if field == "" {
				continue
			}
			words := strings.Fields(field)
			if len(words) == 0 || len(words) > 4 {
				continue
			}
			first := words[0]
			runes := []rune(first)
			if len(runes) < 4 || !unicode.IsUpper(runes[0]) {
				continue
			}
			if noiseWords[strings.ToLower(first)] {
				continue
			}
			if seen[strings.ToLower(first)] {
				continue
			}
			seen[strings.ToLower(first)] = true
			out = append(out, first)
		}
	}
	return out
}

func flatten(entries []Entry) []Entry {
	var out []Entry
	var walk func([]Entry)
	walk = func(list []Entry) {
		for _, e := range list {
			out = append(out, e)
			walk(e.Children)
		}
	}
	walk(entries)
	return out
}

func describeEntries(entries []Entry) string {
	var parts []string
	for _, e := range flatten(entries) {
		if d := e.Describe(); d != "" {
			parts = append(parts, d)
		}
		if len(parts) >= 8 {
			parts = append(parts, "…")
			break
		}
	}
	return strings.Join(parts, "; ")
}

func containsAny(haystack string, needles ...string) bool {
	for _, n := range needles {
		if strings.Contains(haystack, n) {
			return true
		}
	}
	return false
}

func truncate(s string, n int) string {
	s = collapseSpace(s)
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}
