package translate

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/biodream-llc/perfuse/internal/mirth"
)

// Filters and transformers.
//
// The judgement here is what to translate and what to leave as a script. Perfuse
// runs Mirth's JavaScript unchanged, which changes the calculation entirely: there
// is no pressure to rewrite a script into something that looks equivalent, and
// rewriting is exactly where a translator introduces a difference nobody notices.
//
// So a step is translated only when its meaning is unambiguous — a Mapper that
// copies one field to another, a RuleBuilder comparison — and carried over
// verbatim otherwise.

// buildFilter turns Mirth filter rules into a Perfuse filter expression.
func (b *builder) buildFilter(f mirth.Filter, where string) string {
	if len(f.Rules) == 0 {
		return ""
	}

	var parts []string
	var scripted []mirth.Rule

	for _, rule := range f.Rules {
		switch rule.Kind {
		case mirth.RuleBuilder:
			expr, ok := b.ruleExpression(rule, where)
			if !ok {
				continue
			}
			join := "and"
			if strings.EqualFold(rule.Operator, "OR") {
				join = "or"
			}
			if len(parts) == 0 {
				parts = append(parts, expr)
			} else {
				parts = append(parts, join, expr)
			}
			b.counts.FilterRules++

		case mirth.RuleJavaScript:
			scripted = append(scripted, rule)

		default:
			b.note("warning", where, fmt.Sprintf(
				"filter rule %d is a %s, which was not translated", rule.Sequence, rule.RawKind),
				"Check what it did and add an equivalent filter or script")
		}
	}

	if len(scripted) > 0 {
		// A JavaScript filter rule becomes a script filter rather than being
		// approximated. The Perfuse filter language has no function calls on
		// purpose, so anything beyond a comparison genuinely cannot be expressed
		// there and pretending otherwise would be a silent behaviour change.
		b.note("info", where, fmt.Sprintf(
			"%d filter rule(s) are JavaScript and were carried over as a script filter, "+
				"which runs unchanged", len(scripted)),
			"")
		b.scriptFilter = append(b.scriptFilter, scripted...)
	}

	if len(parts) == 0 {
		return ""
	}
	return strings.Join(parts, " ")
}

// ruleExpression translates one RuleBuilder rule.
func (b *builder) ruleExpression(rule mirth.Rule, where string) (string, bool) {
	path := b.pathFor(rule.Field, where)
	if path == "" {
		return "", false
	}

	// Mirth stores rule values as JavaScript literals, so they arrive with their
	// quotes attached. Quoting them again produces a filter that compares against a
	// string containing quote characters and silently never matches, which is the
	// worst kind of translation bug: the channel runs and drops everything.
	values := make([]string, 0, len(rule.Values))
	for _, v := range rule.Values {
		values = append(values, unquoteLiteral(v))
	}

	cond := strings.ToUpper(strings.TrimSpace(rule.Condition))

	switch cond {
	case "EXISTS":
		return path + " exists", true
	case "NOT_EXIST", "NOT EXIST", "NOT_EXISTS":
		return path + " empty", true

	case "EQUALS":
		if len(values) == 0 {
			return "", false
		}
		if len(values) == 1 {
			return fmt.Sprintf("%s == %s", path, quote(values[0])), true
		}
		// Mirth's EQUALS with several values means any of them, which is what our
		// `in` operator says more clearly than a chain of ors.
		return fmt.Sprintf("%s in [%s]", path, quoteList(values)), true

	case "NOT_EQUAL", "NOT EQUAL", "NOT_EQUALS":
		if len(values) == 0 {
			return "", false
		}
		if len(values) == 1 {
			return fmt.Sprintf("%s != %s", path, quote(values[0])), true
		}
		return fmt.Sprintf("not %s in [%s]", path, quoteList(values)), true

	case "CONTAINS":
		if len(values) == 0 {
			return "", false
		}
		// Our language has no `contains` in filters, only `matches`. A regex built
		// from the literal is exact, provided the literal is escaped — an
		// unescaped value containing a dot would silently match more than it should.
		return fmt.Sprintf("%s matches %s", path,
			quote(regexp.QuoteMeta(values[0]))), true

	case "NOT_CONTAIN", "NOT CONTAIN", "NOT_CONTAINS":
		if len(values) == 0 {
			return "", false
		}
		return fmt.Sprintf("not %s matches %s", path,
			quote(regexp.QuoteMeta(values[0]))), true

	default:
		b.note("warning", where, fmt.Sprintf(
			"filter rule %d uses the condition %q, which has no direct equivalent",
			rule.Sequence, rule.Condition),
			"Write the filter by hand for this rule")
		return "", false
	}
}

// pathFor converts a Mirth field reference into a Perfuse path.
//
// Mirth writes these as E4X expressions such as msg['PID']['PID.3']['PID.3.1'], and
// this is the one place a mechanical conversion is safe: the shape is generated by
// the rule builder rather than written by hand, so it is regular.
func (b *builder) pathFor(field, where string) string {
	field = strings.TrimSpace(field)
	if field == "" {
		return ""
	}

	// Pull out the bracketed names: PID, PID.3, PID.3.1.
	parts := bracketNames.FindAllStringSubmatch(field, -1)
	if len(parts) == 0 {
		b.note("warning", where, fmt.Sprintf(
			"could not work out which field %q refers to", collapse(field)),
			"Write this comparison by hand")
		return ""
	}

	var names []string
	for _, p := range parts {
		names = append(names, p[1])
	}

	// The first name is the segment; the rest carry their own numbering, so the
	// last one is the most specific and is all we need.
	segment := names[0]
	last := names[len(names)-1]

	if last == segment {
		// Only the segment was named, which in a filter means "is the segment
		// present".
		return segment + "-1"
	}

	// PID.3.1 becomes PID-3.1, which is the notation used everywhere else here.
	rest := strings.TrimPrefix(last, segment+".")
	if rest == last {
		b.note("warning", where, fmt.Sprintf(
			"the field reference %q does not follow the usual SEG.N.M shape", last),
			"Check the translated path")
		return ""
	}

	pieces := strings.SplitN(rest, ".", 2)
	if len(pieces) == 1 {
		return segment + "-" + pieces[0]
	}
	return segment + "-" + pieces[0] + "." + pieces[1]
}

var bracketNames = regexp.MustCompile(`\['([^']+)'\]`)

// quietPath is pathFor without the reporting, for places where not being a field
// is an ordinary outcome rather than something to flag.
func quietPath(field string) string {
	silent := &builder{}
	return silent.pathFor(field, "")
}

// bareFieldPath resolves a reference only when it is nothing but a field.
//
// This distinction is the difference between a correct translation and a quietly
// wrong one. The mapping
//
//	msg['PID']['PID.5']['PID.5.1'].toString().toUpperCase().substring(0, 10)
//
// contains a field reference, and a resolver that stops at the brackets happily
// reports PID-5.1 — turning an upper-casing, truncating transformation into a plain
// copy that changes nothing. The message still flows, the channel still looks
// right, and a field arrives untransformed. So anything after the last bracket
// other than a trailing .toString() means this is an expression, and an expression
// belongs in the script where it will run exactly as it did before.
func bareFieldPath(field string) string {
	trimmed := strings.TrimSpace(field)
	trimmed = strings.TrimSuffix(trimmed, ";")
	trimmed = strings.TrimSpace(trimmed)

	last := strings.LastIndex(trimmed, "]")
	if last < 0 {
		return ""
	}

	tail := strings.TrimSpace(trimmed[last+1:])
	switch tail {
	case "", ".toString()", ".toString():":
		// A trailing toString() is how Mirth's own rule builder writes a plain field
		// read, so it carries no meaning of its own.
	default:
		return ""
	}

	// And nothing may precede the reference either: "'X' + msg[...]" is a
	// concatenation, not a field.
	head := strings.TrimSpace(trimmed[:strings.Index(trimmed, "[")])
	switch head {
	case "msg", "tmp", "":
	default:
		return ""
	}

	return quietPath(trimmed)
}

// buildTransformations turns transformer steps into declarative steps where the
// meaning is unambiguous.
func (b *builder) buildTransformations() string {
	steps := b.ch.Source.Transformer.Steps
	if len(steps) == 0 {
		return ""
	}

	var lines []string

	for _, step := range steps {
		where := fmt.Sprintf("source step %d (%s)", step.Sequence, step.Name)

		switch step.Kind {
		case mirth.StepMapper:
			line, ok := b.mapperStep(step, where)
			if !ok {
				continue
			}
			lines = append(lines, line)
			b.counts.Declarative++

		case mirth.StepJavaScript:
			// Carried over rather than interpreted. Perfuse runs it unchanged, so
			// there is nothing to gain from guessing at its meaning and a great deal
			// to lose.
			b.scriptSteps = append(b.scriptSteps, step)
			b.counts.Scripted++

		case mirth.StepXSLT:
			b.note("blocker", where,
				"the step is an XSLT transformation, which Perfuse does not implement",
				"Rewrite it as declarative steps or as JavaScript, whichever is shorter")

		case mirth.StepExternalScript:
			b.note("blocker", where, fmt.Sprintf(
				"the step runs an external script from %s, which is not part of the "+
					"channel and was not exported with it", step.Script),
				"Find that file and paste its contents into the channel's script")

		case mirth.StepMessageBuilder:
			// A message builder writes into an outbound template, which Perfuse has
			// no equivalent for: it transforms the message in place.
			b.note("warning", where,
				"the step is a Message Builder, which writes into a separate outbound "+
					"template. Perfuse transforms the message in place and has no outbound "+
					"template",
				"If the built message is the same format as the inbound one, a set or copy "+
					"step does the same job. If it is a different format entirely, this "+
					"channel needs rethinking rather than translating")

		case mirth.StepIterator:
			b.note("warning", where, fmt.Sprintf(
				"the step iterates over repeating fields with %d nested step(s)",
				len(step.Children)),
				"A Perfuse path naming no repetition already addresses all of them, so "+
					"many iterators become a single step. Check whether that is true here")

		default:
			b.note("warning", where, fmt.Sprintf(
				"the step is a %s, which was not translated", step.RawKind),
				"Check what it did and reproduce it")
		}
	}

	if len(lines) == 0 {
		return ""
	}

	var out strings.Builder
	fmt.Fprintln(&out, "\ntransformations:")
	for _, line := range lines {
		out.WriteString(line)
	}
	return out.String()
}

// mapperStep translates a Mapper step.
//
// A Mapper in Mirth assigns a mapping expression to a variable. Two shapes are safe
// to translate: writing into another field, which is a copy, and writing a literal,
// which is a set. Anything else is a JavaScript expression and goes to the script.
func (b *builder) mapperStep(step mirth.Step, where string) (string, bool) {
	mapping := strings.TrimSpace(step.Mapping)
	variable := strings.TrimSpace(step.Variable)

	if mapping == "" {
		b.note("warning", where, "the mapper step has no mapping expression", "")
		return "", false
	}

	// Resolved quietly. A mapper's variable is very often a channelMap name rather
	// than a field, which is not a failure to understand anything, and warning
	// about it would bury the notes that matter under noise.
	target := bareFieldPath(variable)
	source := bareFieldPath(mapping)

	// Field to field: a copy.
	if target != "" && source != "" {
		return fmt.Sprintf("  - description: %s\n    copy: {from: %s, to: %s}\n",
			yamlString(collapse(step.Name)), source, target), true
	}

	// A literal into a field: a set. Only a plain quoted string, because anything
	// else is an expression and evaluating it here would be guessing.
	if target != "" {
		if literal, ok := stringLiteral(mapping); ok {
			return fmt.Sprintf("  - description: %s\n    set: {path: %s, value: %s}\n",
				yamlString(collapse(step.Name)), target, yamlString(literal)), true
		}
	}

	// Mirth mappers commonly assign into channelMap for later steps to read.
	// There is no declarative equivalent, and turning it into one would change when
	// it happens.
	if target == "" && !strings.Contains(variable, "[") {
		b.note("info", where, fmt.Sprintf(
			"the mapper sets the variable %q rather than a field, so it was carried "+
				"over as a script", variable),
			"")
		b.scriptSteps = append(b.scriptSteps, step)
		b.counts.Scripted++
		return "", false
	}

	b.note("info", where,
		"the mapper's expression is not a plain field or literal, so it was carried "+
			"over as a script and runs unchanged",
		"")
	b.scriptSteps = append(b.scriptSteps, step)
	b.counts.Scripted++
	return "", false
}

var stringLiteralRE = regexp.MustCompile(`^\s*['"]([^'"]*)['"]\s*;?\s*$`)

func stringLiteral(s string) (string, bool) {
	m := stringLiteralRE.FindStringSubmatch(s)
	if m == nil {
		return "", false
	}
	return m[1], true
}

func quote(s string) string {
	return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
}

func quoteList(values []string) string {
	var parts []string
	for _, v := range values {
		parts = append(parts, quote(v))
	}
	return strings.Join(parts, ", ")
}

// unquoteLiteral strips the quotes Mirth stores around a rule value.
//
// Only a matched pair, and only when there is nothing outside it. A value that is
// an expression rather than a literal is left alone so it shows up as obviously
// wrong in the output rather than as a plausible-looking string.
func unquoteLiteral(v string) string {
	v = strings.TrimSpace(v)
	if len(v) < 2 {
		return v
	}
	first, last := v[0], v[len(v)-1]
	if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
		inner := v[1 : len(v)-1]
		// Refuse if the inner text carries another quote of the same kind, which
		// means this is not a simple literal.
		if !strings.ContainsRune(inner, rune(first)) {
			return inner
		}
	}
	return v
}
